# An action to push templates to coder server

name: Deeplearning Nvidia

on:
  push:
    branches:
      - main
    paths:
      - "deeplearning-nvidia/main.tf"
      - ".github/workflows/deeplearning-nvidia.yaml"
      - "deeplearning-nvidia/images/*"
  pull_request:
    branches:
      - main
    paths:
      - "deeplearning-nvidia/main.tf"
      - ".github/workflows/deeplearning-nvidia.yaml"
      - "deeplearning-nvidia/images/*"
  workflow_dispatch:

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest short commit SHA
        id: get_commit_sha
        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: update coder template
        uses: matifali/update-coder-template@latest
        with:
          CODER_URL: ${{ secrets.CODER_URL }}
          CODER_TEMPLATE_NAME: "deeplearning-nvidia"
          CODER_TEMPLATE_DIR: "deeplearning-nvidia"
          CODER_TEMPLATE_VERSION: ${{ steps.get_commit_sha.outputs.sha_short }}
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
